services:
  # 1. api-prober Go Application
  api-prober:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_prober_app
    restart: unless-stopped
    environment:
      # Worker pool and job queue scaling
      - WORKERS=50
      - QUEUE_SIZE=10000
      
      # HTTP connection pooling limits
      - MAX_IDLE_CONNS=1000
      - MAX_IDLE_CONNS_PER_HOST=100
      
      # Frequency of probes per target
      - PROBE_INTERVAL_SECONDS=2
    expose:
      - "8080"
    volumes:
      - ./targets.csv:/app/targets.csv:ro
    networks:
      - monitoring
    depends_on:
      - httpbin
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.02'
          memory: 20M

  # 2. Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus-data:/prometheus
    expose:
      - "9090"
    networks:
      - monitoring

  # 3. Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost/dashboard/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/api_prober_dashboard.json
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - monitoring

  # 4. Httpbin
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin_server
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - monitoring

  # 5. Nginx Gateway
  nginx:
    image: nginx:alpine
    container_name: api_prober_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" # for secure https encryption opened    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro # mount tls certificates to the container
    depends_on:
      - grafana
      - api-prober
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.33.0
    container_name: api_prober_alertmanager
    restart: unless-stopped
    # Wir reichen die funktionierenden Keys aus deiner .env weiter
    environment:
      - PUSHOVER_USER_KEY=${PUSHOVER_USER_KEY}
      - PUSHOVER_API_TOKEN=${PUSHOVER_API_TOKEN}
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.template.yml:ro
    # Ein fliegender Wechsel: Platzhalter ersetzen und Alertmanager starten
    entrypoint: >
      /bin/sh -c "sed -e 's/PUSHOVER_USER_KEY_PLACEHOLDER/'\"$${PUSHOVER_USER_KEY}\"'/g' -e 's/PUSHOVER_API_TOKEN_PLACEHOLDER/'\"$${PUSHOVER_API_TOKEN}\"'/g' /etc/alertmanager/alertmanager.template.yml > /tmp/alertmanager.yml && exec /bin/alertmanager --config.file=/tmp/alertmanager.yml --storage.path=/alertmanager"
    networks:
      - monitoring

volumes:
  grafana-storage:
  prometheus-data:

networks:
  monitoring:
    driver: bridge