events {}

http {
    server {
        listen 80;

        location /dashboard/ {
            proxy_pass http://grafana:3000;
            # Tell Grafana explicitly that the external port is 80
            proxy_set_header Host $host:80; 
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /metrics {
            proxy_pass http://quadrasign:8080/metrics;
            proxy_set_header Host $host;
        }
    }
}