apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # Reaches the Prometheus container inside the Docker network
    isDefault: true
    editable: true